CREATE SCHEMA SS_1;

DROP TABLE IF EXISTS SHARDING_TEST;

CREATE TABLE SHARDING_TEST
(
	id BIGINT(20) NOT NULL COMMENT '主键ID',
	REG_DATE DATE NULL DEFAULT NULL COMMENT '注册日期',
	name VARCHAR(255) NULL DEFAULT NULL COMMENT '姓名',
    SHARDING_KEY VARCHAR(50) NULL DEFAULT NULL COMMENT '分片id',
	PRIMARY KEY (id)
);