
{
    size: ${size},
    userName:${user.userName},
    age:10,
    books:[<#list paper as item>"${item.userName}" <#sep>,</#list>],
    complexObj:[<#list paper as item>{userName:"${item.userName}"} <#sep>,</#list>],
    complexMap:{<#list paper as item>"${item.userName}":{"userName":"${item.userName}"} <#sep>,</#list>},
    mac:"${_Sign_(size,user.userName,send_BANK,account)}",
    testMap:[<#list testMap?keys as key> {${key}:"${testMap["${key}"]}"}<#sep>,</#list>],
    OUTSYS_TX_CODE:${outsys_TX_CODE},
    RET_EXPLAIN:${ret_EXPLAIN},
    SEND_BANK:${send_BANK},
    ACCOUNT:${account},
    CHNL_CODE:${chnl_CODE},
    TRADEFLAG:${tradeflag},
    SEQNO:${seqno},
    CLR_DATE:${clr_DATE},
    RCV_BKNO:${rcv_BKNO},
    BUSI_CODE:${busi_CODE},
    TRADEFLAG1:${tradeflag1},
    TRADEFLAG2:${tradeflag2},
    TRADEFLAG3:${tradeflag3},
    TRADEFLAG4:${tradeflag4},
    TRADEFLAG5:${tradeflag5},
    TRADEFLAG6:${tradeflag6},
    TRADEFLAG7:${tradeflag7},
    TRADEFLAG8:${tradeflag8},
    TRADEFLAG9:${tradeflag9},
    TRADEFLAG10:${tradeflag10},
    TRADEFLAG11:${tradeflag11},
    TRADEFLAG12:${tradeflag12},
    TRADEFLAG13:${tradeflag13},
    TRADEFLAG14:${tradeflag14},
    TRADEFLAG15:${tradeflag15},
    TRADEFLAG16:${tradeflag16},
    TRADEFLAG17:${tradeflag17},
    TRADEFLAG18:${tradeflag18},
    TRADEFLAG19:${tradeflag19},
    TRADEFLAG20:${tradeflag20}

}